CREATE TABLE `example` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(254) NOT NULL,
  `beschreibung` text DEFAULT NULL,
  `auswahl` int(11) DEFAULT NULL,
  `zeitstempel` datetime DEFAULT NULL,
  `betrag` decimal(10, 2) DEFAULT NULL,
  `nachkomma` decimal(10, 10) DEFAULT NULL,
  `checkbox` int(11) DEFAULT NULL,
  `radio` int(11) DEFAULT NULL,
  `teil1` varchar(254) NOT NULL,
  `teil2` varchar(254) NOT NULL,
  `longtext` varchar(254) NULL,
  `count1` decimal(10, 6) DEFAULT NULL,
  `count2` decimal(10, 6) DEFAULT NULL,
  `testitest` varchar(254) NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

INSERT INTO
  `example` (
    `name`,
    `beschreibung`,
    `auswahl`,
    `zeitstempel`,
    `betrag`,
    `nachkomma`,
    `checkbox`,
    `radio`,
    `teil1`,
    `teil2`,
    `longtext`,
    `count1`,
    `count2`,
    `testitest`
  )
VALUES
  (
    'Titel A',
    'I walked across an empty land',
    '2',
    '2021-08-05 09:21:13.000000',
    '500',
    '0.00065',
    '1',
    '0',
    'Hans',
    'Wurst',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    50,
    70,
    'Test 1'
  ),
  (
    'Titel B',
    'I knew the pathway like the back of my hand',
    '1',
    '2021-01-23 09:21:13.000000',
    '299',
    '0.231',
    '1',
    '3',
    'Dual',
    'text',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    20,
    56,
    'Test 2'
  ),
  (
    'Titel C',
    'I felt the earth beneath my feet',
    '3',
    '2021-06-12 09:21:13.000000',
    '13',
    '0.5342',
    '1',
    '4',
    'Some',
    'body',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    15.544,
    59.955455,
    'Test 3'
  ),
  (
    'Titel D',
    'Sat by the river and it made me complete',
    '2',
    '2021-05-26 09:21:13.000000',
    '100',
    '123.23',
    '0',
    '1',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 4'
  ),
  (
    'Titel E',
    'Oh simple thing, where have you gone?',
    '1',
    '2021-01-14 09:21:13.000000',
    '232',
    '0.00065',
    '1',
    '3',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 5'
  ),
  (
    'Titel F',
    'I''m getting old and I need something to rely on',
    '3',
    '2021-07-26 09:21:13.000000',
    '231',
    '0.324',
    '0',
    '1',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 6'
  ),
  (
    'Titel G',
    'So tell me when you''re gonna let me in',
    '2',
    '2022-07-26 09:21:13.000000',
    '2414',
    '564.00065',
    '1',
    '2',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 7'
  ),
  (
    'Titel H',
    'I''m getting tired and I need somewhere to begin',
    '4',
    '2021-07-26 09:21:13.000000',
    '1241',
    '0.52',
    '1',
    '3',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 8'
  ),
  (
    'Titel I',
    'I came across a fallen tree',
    '2',
    '2021-07-26 09:21:13.000000',
    '4243',
    '5.5',
    '0',
    '0',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 9'
  ),
  (
    'Titel J',
    'I felt the branches of it looking at me',
    '1',
    '2021-07-23 09:21:13.000000',
    '23',
    '34.342',
    '1',
    '2',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 10'
  ),
  (
    'Titel K',
    'Is this the place we used to love?',
    '3',
    '2012-07-10 09:21:13.000000',
    '876',
    '0.42',
    '4',
    '3',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 11'
  ),
  (
    'Titel L',
    'Is this the place that I''ve been dreaming of?',
    '2',
    '2021-07-26 09:21:13.000000',
    '234',
    '0.78',
    '0',
    '2',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 12'
  ),
  (
    'Titel M',
    'And if you have a minute, why don''t we go',
    '5',
    '2021-07-03 09:21:13.000000',
    '100',
    '0.234',
    '1',
    '3',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 13'
  ),
  (
    'Titel N',
    'Talk about it somewhere only we know?',
    '2',
    '2021-07-04 09:21:13.000000',
    '86',
    '0.00065',
    '1',
    '1',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 14'
  ),
  (
    'Titel O',
    'This could be the end of everything',
    '6',
    '2021-07-05 09:21:13.000000',
    '34',
    '0.24',
    '1',
    '3',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 15'
  ),
  (
    'Titel P',
    'So why don''t we go somewhere only we know?',
    '2',
    '2021-07-07 09:21:13.000000',
    '23',
    '0.00065',
    '1',
    '0',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 16'
  ),
  (
    'Titel Q',
    'I don''t wanna wake up',
    '7',
    '2021-07-26 09:21:13.000000',
    '678',
    '7.2',
    '0',
    '3',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 17'
  ),
  (
    'Titel R',
    'Grab a brush and put a little make-up',
    '2',
    '2021-07-26 09:21:13.000000',
    '4',
    '0.86',
    '1',
    '3',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 18'
  ),
  (
    'Titel S',
    'Hide the scars to fade away the shake-up',
    '8',
    '2021-07-26 09:21:13.000000',
    '1050',
    '8.6',
    '1',
    '3',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 19'
  ),
  (
    'Titel T',
    'I don''t think you trust',
    '7',
    '2021-07-26 09:21:13.000000',
    '768',
    '0.113',
    '0',
    '3',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 20'
  ),
  (
    'Titel U',
    'In',
    '3',
    '2021-07-26 09:21:13.000000',
    '54',
    '0.2876',
    '1',
    '3',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 21'
  ),
  (
    'Titel V',
    'My',
    '6',
    '2021-07-26 09:21:13.000000',
    '456',
    '556.867',
    '0',
    '3',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 22'
  ),
  (
    'Titel W',
    'Self-righteous suicide',
    '6',
    '2021-07-26 09:21:13.000000',
    '78',
    '0.234',
    '1',
    '3',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 23'
  ),
  (
    'Titel X',
    'I Cry',
    '5',
    '2021-07-26 09:21:13.000000',
    '56756',
    '0.324',
    '1',
    '3',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 24'
  ),
  (
    'Titel Y',
    'When angels deserve to',
    '3',
    '2021-07-26 09:21:13.000000',
    '7',
    '30.00065',
    '1',
    '3',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 25'
  ),
  (
    'Titel Z',
    'Diiiiiiiiiieeeee',
    '4',
    '2021-07-26 09:21:13.000000',
    '876',
    '4.25',
    '1',
    '3',
    'Zusammen',
    'setzen',
    'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takima',
    10,
    20,
    'Test 26'
  );